default_stages: [ pre-commit, post-checkout ]
default_install_hook_types: [ pre-commit, post-checkout ]
exclude: ^.idea/.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # file type specific checks
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix", "--no-sort-keys" ]
      - id: check-toml
      - id: check-executables-have-shebangs
      # general files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: [ "--maxkb=2048" ]
      # python checks
      - id: name-tests-test
        args: [ "--pytest-test-first" ]
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      # python checks
      - id: python-no-eval
      - id: python-no-log-warn
      # rst checks
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint-fix
        args: [ "--disable", "MD033" ]
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry run bandit
        language: system
        types: [ python ]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py310-plus
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
      - id: pylint
        name: pylint
        entry: poetry run pylint -rn -sn
        language: system
        types: [ python ]
      - id: poetry-sync
        name: poetry-sync
        entry: poetry install --sync --with dev
        language: system
        always_run: true
        stages:
          - post-checkout
